#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -n "$GITHUB_ACTIONS" ]; then
  echo "Running in GitHub Actions, skipping pre-commit hook"
  exit 0
fi

npm run check || {
  echo "Please fix by running 'npm run check:fix' and commit again."
  exit 1
}